- lib/samsam.js
- test/samsam-test.js
When matching two similar arrays of objects which are mis-ordered, the "arrayContains" function goes beyond the bounds of the left hand side array and causes the match to blow up.
This PR adds a safety check in the array iteration.
> Keep within array bounds when matching arrays

- .travis.yml
- appveyor.yml
- lib/samsam.js
- test/samsam-test.js
The match-function does not handle date objects and yields false positives when matching objects with different dates.
Example:
```javascript
samsam.match({d = new Date(2017, 8, 28)}, {d: new Date(2017, 8, 29});
// => true
```
This PR copies the date handling from `deepEqual`.
> Match dates

- README.md
I've activated coveralls for this repository. This PR adds the badge to `README.md`
1. Observe that there's a coveralls report at the end of the pull request
2. Once merged, verify that the badge in `README.md` displays a coverage value
> Add coveralls badge to README.md

- lib/samsam.js
- lib/samsam.test.js
- package.json
RE #25
In an attempt to clean `deepEqual` and `match` methods it was deemed better to ensure that they always return `true`/`false`.
I've:
- added test cases for these changes
- updated the other tests to use `asset.deepEqual` as making the changes didn't make any tests fail due to the weak type checking of `referee.assert` and `referee.refute`
- updated the tests name to be more explicit as to what the behaviour of `samsam` returns.
> Ensure deepEqual and match always return true/false

- docs/index.md
- lib/samsam.js
- lib/samsam.test.js
This removes `isDate` from being exposed and updates the internal method to check if `value instanceof Date`. It resolves #30.
> Remove isDate method from being exported

- lib/deep-equal.js
- lib/deep-equal.test.js
- lib/get-class-name.js
- lib/get-class-name.test.js
This feature adds the comparision of the `name` property of a given objects `constructor` if there is any.
See #37, sinonjs/sinon#1882
Check if the names of the constructor of two given objects are unequal and return `false` if so. This is done by a helper function `getClassName()` which returns the name of the constructor or `null`.
3. `npm run test`
> feat(deepEqual): compare constructor name of objects

- lib/get-class-name.js
- lib/get-class-name.test.js
getClassName() does not currently work with objects returned by the Node v6 querystring builtin module, which does some weird things to the object.  When run on those objects, the module throws an exception, since `value.constructor` is `undefined`, even though the object does have a prototype defined.  This is breaking sinon mock expectations against those types of objects for us.
See https://github.com/nodejs/node/blob/v6.x/lib/querystring.js#L20
If what this library wants to return is the constructor name, I think it would be simpler just to check if that exists and return that.  In this case, I believe that `null` is the correct return type, since the object is not intended to represent a specific instance (and in more recent versions of Node, `querystring.parse()` just uses …
> Fix getting class name of Node v6 querystring object

- lib/match.js
- lib/match.test.js
This fixes an issue where `samsam.match(null, { not: 1 })` would throw `TypeError: Cannot read property 'not' of null`.
3. `npm test`
> Handle null match argument

- lib/match.js
- lib/match.test.js
__BREAKING:__ This brings the `samsam.match` implementation closer to how `sinon.match` behaves. Nested object where recursively compared using `samsam.match` itself. This change uses `samsam.deepEqual` for recursive checks instead. If matching logic is desireable on nested objects, `samsam.createMatcher` can be used which is now recognized.
This fixes https://github.com/sinonjs/referee/issues/54
3. `npm t`
> Fix nested array match

- package.json
Currently, samsam depends on exact versions of `@sinonjs/commons` and `lodash.get`, which prevents npm from deduping those packages if other, compatible versions of them are dependents of other packages in the tree.
For example, sinon currently [depends on](https://github.com/sinonjs/sinon/blob/9741f41f94d45785daed11a129c080ea04f7f78e/package.json#L58) `@sinonjs/commons@^1.2.0`, meaning that `npm install sinon` unnecessarily installs two different versions of `@sinonjs/commons`.
Generally, unless there's a specific reason to pin dependencies to exact versions, could sinon and its associated libraries try to depend on version ranges instead?
(Incidentally, Lodash's compiled zero-dependency packages are considered [deprecated](https://github.com/lodash/lodash/wiki/Roadmap#v500-2018) in …
> Depend on version ranges rather than exact versions

- lib/create-set.js
- lib/deep-equal.js
- lib/get-class-name.js
- lib/iterable-to-string.js
- lib/match.js
- lib/matcher.js
While working on #55 we found some places where we can use functionality from the `@sinonjs/commons` package.
- Strigngs
- Replace `someVar.toString()` with `valueToString(someVar)`
- Replace `String(someVar)` with `valueToString(someVar)`
- Arrays
- Replace `Array.isArray(someVar)`
3. `npm test`
> Some improvements

- lib/matcher.js
- lib/matcher.test.js
This PR is intended to study and improve the behaviour of matching arrays `deepEqual`.
First this just adds a failing testcase for nested arrays as described in #54.
Improved `array.deepEquals` to call itself when given an array as `element`. All other elements will be checked by stricked equality (`===`) as usual.
*Note:* I used `Array.isArray` to determine if an element is an array. I am not quite sure if this is a prefered way to do so ❓ 😕 
3. `npm test`
> Improve deep equality matching on arrays

- lib/matcher.js
- lib/matcher.test.js
use the `deepEqual` function for `expected` and `actual` element when comparing arrays.
Also extend test case for nested arrays
See #54 #55 
3. `npm test`
> refactor: use deepEqual for array elements

- lib/samsam.js
This is for a possible refactoring in formatio to use the provided isSet method
from samsam
See: sinonjs/formatio#22
Use `isSet` method in [formatio](https://github.com/sinonjs/formatio/blob/07e2b54e573a199b1006dd223160c66bca3eb870/lib/formatio.js#L88) to reduce code duplication.
> feat: export isSet method

- docs/index.md
Because `isSet` is now exported, add a small description to the documentation.
Further this refactores the block of the _Predicate functions_ to use `value` as an identifier for a given parameter.
3. Check the docs
> docs: add isSet

- lib/matcher.js
- lib/matcher.test.js
The signature for `samsam.createMatcher` is `createMatcher(expectation[, message])`. But since we don't type check the optional `message` argument (or the existence of subsequent arguments) there is no protection against mistakes like doing...
```javascript
sinon.assert.calledWith(
myService,
sinon.match(myCustomMatcher, sinon.match.func) // <--- wrongly placed parens
);
```
...instead of...
```javascript
sinon.assert.calledWith(
myService,
sinon.match(myCustomMatcher),
sinon.match.func
);
```
This PR adds the missing checks.
3. `npm test`
> Check createMatcher arguments

- AUTHORS
- docs/index.md
- lib/deep-equal.js
- lib/deep-equal.test.js
Fix issue [sinon#1974](https://github.com/sinonjs/sinon/issues/1974) by asserting that two objects are not deeply equal if the expectation object contains different [symbolic](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) keys than the actual object.
Previously, `deepEqual` would just iterate over the `Object.keys` of the expectation object and compare them to the actual object. This PR changes this so that the object's own property symbols are also considered. Per @mantoni's suggestion, this will assert deep equal if the actual object contains additional symbolic properties that are missing from the expectation.
After making this change, [this unit test](https://github.com/sinonjs/samsam/blob/master/lib/deep-equal.test.js#L425) failed. This is …
> Evaluate symbolic keys for deep equality assertion

- lib/deep-equal.test.js
Fixes test cases that broke due to #64.
The reason the build on the PR did not break was that the browser tests don't run on PRs from forks. They only run on PRs from branches. This is due to some security constraints with our secret key for SauceLabs.
Feature detecting `Symbol` and conditionally execute the corresponding tests.
3. `npm run test-cloud`
> Fix Symbol related tests for IE 11

- lib/deep-equal.js
This PR fixes lack of caching of `Object.getOwnPropertySymbols` in `deepEqualCyclic`, as caching standard library functions is advised in the below checklist for authors.
I just tried updating my project from sinon 7.2.7 to sinon 7.3.0, a change that includes addition of the line that the PR changs, and I get a lot of errors like this :
```
'Unhandled promise rejection', TypeError: undefined is not a constructor (evaluating 'getOwnPropertySymbols(expectationObj)')
deepEqual@http://localhost:9876/absolute/Users/angelika/myproject/node_modules/sinon/pkg/sinon.js?911775df668393e499a0995e2789094c48727cc3:4395:40
deepEqualCyclic@http://localhost:9876/absolute/Users/angelika/myproject/node_modules/sinon/pkg/sinon.js?911775df668393e499a0995e2789094c48727cc3:4493:7
...
```
Such a situation could …
> Use cached `getOwnPropertySymbols` consistently

- lib/deep-equal.test.js
This PR adds tests discovered to be missing while working on #69.
> Improve tests using Sets with deepEqual

- .gitignore
- lib/deep-equal.js
- lib/deep-equal.test.js
- lib/is-map.js
This PR fixes #67, where using deepEqual on non-equal `Map`  instances would return `true`
> Fix #67: Add support for Map

- .eslintrc.yaml
- eslint-local-rules.js
- lib/create-set.js
- lib/deep-equal.js
- lib/deep-equal.test.js
- lib/is-subset.js
- lib/match.js
- lib/match.test.js
- lib/matcher.js
- lib/matcher.test.js
- package-lock.json
- package.json
This PR upgrades ESLint and all related packages to latest versions.
In order to prepare for linting JSDoc, I thought it would be a good idea to get `samsam` caught up with the other projects.
That turned out to be more work than I anticipated 😮 
* Upgrade ESLint and related plugins and configs
* Fix lint violations
* Import `no-prototype-methods` from `sinon`
* Fix even more lint violations
3. `npm run lint`
1. `npm test``
1. Observe that all is green
> Upgrade ESLint and all dependencies

- lib/create-set.test.js
- package-lock.json
- package.json
This PR adds explicit tests of `createSet` to get it's coverage to 100%.
Trying to get test coverage to 100%, so we can lock it there.
* Upgrade `@sinonjs/referee` to latest to get the `isSet` assertion
* Add tests
1. `npm install`
1. Put a `.only` in the first `describe` in `create-set.test.js`
1. `npm run test-coverage`
1. Observe that the test coverage of `createSet` is 100%, when only its tests are run
```
-----------------------|----------|----------|----------|----------|-------------------|
File                   |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-----------------------|----------|----------|----------|----------|-------------------|
All files              |    31.78 |     4.78 |     8.41 |    31.78 |                   | …
```
> Improve test coverage of createSet

- lib/create-set.test.js
Don't use array.includes, it is not supported in IE11
2. `npm run test-cloud`
3. Observe that the build doesn't fail in IE11
> Fix broken build in IE11

- lib/is-element.test.js
This PR makes a few improvements to `is-element.test.js`
Improve test isolation in order to allow future work to re-order tests.
During work in #82 I discovered that this test is sensitive to load order.
* Increase test isolation be ensuring that `is-element.js` detects the DOM set up in the test harness.
* Also improve readability of the test file.
1. Observe all tests pass
> Improve is-element.test.js

- lib/iterable-to-string.js
* Reduce nesting of functions
This makes the code easier to reason about
1. Observe tests are still passing
> Refactor: iterableToString

- README.md
Since ab993214b94d013072848902b26bb92cf8173e79 we have moved from
Coveralls to Codecov.
This updates the badge to point to Codecov.
1. View the `README.md`
2. Observe that the coverage badge points to Codecov
> Replace coverage badge

- lib/create-matcher.js
- lib/create-matcher/assert-matcher.js
- lib/create-matcher/assert-method-exists.js
- lib/create-matcher/assert-type.js
- lib/create-matcher/is-iterable.js
- lib/create-matcher/is-matcher.js
- lib/create-matcher/match-object.js
- lib/create-matcher/matcher-prototype.js
- lib/create-matcher/type-map.js
This PR is a partial refactoring of `create-matcher.js`.
In order to make the code easier to understand and test, we need to split it up into manageable chunks.
As can be seen in the diagram below, there are a lot of dependencies between the different parts. Most interesting is the circular dependency between `matcher-prototype` and `create-matcher.
I've overcome that problem by only using `require("../create-matcher")` inside the functions of `matcher-prototype` instead of at the top of the file.
```
┌───────────────────┐   
│ matcher-prototype │◀━┓
└───────────────────┘  ┃
▲            ┃
│            ┃
│            ┃
┌───────────────────┐         ┌───────────────────┐  ┃
│  assert-matcher   │────────▶│    is-matcher     │  ┃
└───────────────────┘         └───────────────────┘  ┃
▲ …
```
> Refactoring create-matcher

- lib/is-arguments.test.js
- lib/is-element.test.js
- package-lock.json
- package.json
Fix the _Headless_ Tests (`mochify`)
I'm not really sure if this is the apropriate fix, but now they pass
3. `npm run test-headless`
> Fix headless tests

- .eslintrc.yaml
- lib/match.js
- lib/match.test.js
This PR adds Support for [`BigInt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt)
3. `npm test`
> add support for BigInt

- lib/match.js
- lib/match.test.js
Support comparing [`Symbol`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) in `samsam`.
Discussion: #112 
3. `npm test`
> add support for comparing symbols

- lib/deep-equal.js
- lib/deep-equal.test.js
This PR increases coverage for `deepEqual` to 💯 
The coverage could not be reached because `jsdom` was not properly applied in `deep-equal.test.js` and therefore [`isElement`](https://github.com/sinonjs/samsam/blob/master/lib/deep-equal.js#L97) always returned `false`. Now there is a dedicated Test suite that applies `jsdom` and reloads all files.
3. `npm run test`, `npm run test-coverage`
> Deep equal coverage

- lib/match.js
The else path is a fallback for when we've managed somehow to find the impossible combination of arguments to make this pass, despite the input validation
Not sure it is even possible to get to the else path
1. `npm ci`
1. `npm run test-coverage`
1. Observe coverage reported as 100% for statements, branches, functions and lines
> Ignore impossible else path

- .circleci/config.yml
- lib/engine-can-detect-arguments.js
- package.json
This ensures that no branch will get merged that doesn't have 100% test coverage.
This can be merged after #132 has been merged, which brings coverage up to 100%.
1. Update this branch with latest from #132 (or wait until that has merged into `master`)
1. `npm ci`
1. `npm run test-check-coverage`
1. Observe there is no error message
1. `echo $?`
1. Observe that the status code is zero
1. Observe that CircleCI passes the build (green)
> Add test-check-coverage and use it in CI

- lib/samsam.test.js
When the runtime doesn't support the `.name` property on `Functions`,
skip the API tests.
Make tests pass in IE11
When running tests in IE11, I was seeing these failures:
```
8) samsam API
should have a binary method named `createMatcher`:
AssertionError: [assert.equals] undefined expected to be equal to createMatcher
at fail (node_modules/@sinonjs/referee/lib/create-fail.js:15)
at ctx.fail (node_modules/@sinonjs/referee/lib/define-assertion.js:46)
at assertion (node_modules/@sinonjs/referee/lib/define-assertion.js:68)
at referee[type][name] (node_modules/@sinonjs/referee/lib/define-assertion.js:93)
at Anonymous function (lib/samsam.test.js:9)
9) samsam API
should have a binary method named `deepEqual`:
AssertionError: [assert.equals] undefined expected to be equal to deepEqual
at fail …
```
> Avoid test failures in IE11

- lib/match.js
- lib/match.test.js
This PR adds a warning to not use `samsam.match` with `Map` in un-supporting engines (IE11).
If there's consensus from the maintainers that this is a reasonable solution, then I'll add some tests to the PR.
Prevent obscure errors in IE11 and warn end user that `samsam.match` cannot do anything meaningful when called with `Map` instances in IE11.
When running tests in IE11, I am seeing a bunch of errors because of missing `Array.from`:
```
2) match
Map
returns true for same content in map:
TypeError: Object doesn't support property or method 'from'
at match (lib/match.js:108)
at Anonymous function (lib/match.test.js:527)
3) match
Map
returns true for same complex content in map:
TypeError: Object doesn't support property or method 'from'
at match (lib/match.js:108)
at Anonymous function …
```
> Throw on matching Map in unsupporting engines

- lib/deep-equal.js
- lib/deep-equal.test.js
This PR fixes a failing test in IE11
```
1) deepEqual
with symbol properties
without symbol support
returns true if object missing expected symbolic properties:
AssertionError: [assert.isTrue] Expected false to be true
at fail (node_modules/@sinonjs/referee/lib/create-fail.js:15)
at ctx.fail (node_modules/@sinonjs/referee/lib/define-assertion.js:46)
at assertion (node_modules/@sinonjs/referee/lib/define-assertion.js:68)
at referee[type][name] (node_modules/@sinonjs/referee/lib/define-assertion.js:93)
at Anonymous function (lib/deep-equal.test.js:446)
```
Reading the test more closely, reveals a logical error ... trying to test something with Symbol properties in an engine that doesn't have Symbol support. How would those Symbol properties be created, when the engine doesn't support …
> Remove meaningless test

- lib/is-element.test.js
- package-lock.json
- package.json
Use Option `--no-detect-globals` for `mochify` command in `test-headless`
Based on the suggestion by @mantoni [here](https://github.com/sinonjs/samsam/pull/130#issuecomment-541600189)
3. `npm run test`, `npm run test-headless`
> Exclude jsdom when bundling for headless tests

- docs/index.md
Some quick and easy documentation improvements
- We've been lying about dependencies and IE6 support for some time now.
- The matchers documentation was missing the pre defined matchers. I've copied the relevant section from the Sinon docs.
> Matcher documentation

- lib/match.js
- package.json
Simplify `match` by using `type-detect` and a `switch` statement
The `match` function is getting longer and more complex. This refactoring pulls it back slightly. There is lots more we can do, but I think this is a good start and will allow #143 to get merged sooner.
I think we should make greater use of `type-detect`, and consider using that in all `Sinon` projects, instead of `samsam.isX` functions. Perhaps even create a new major version of `samsam` without these functions.
1. `npm ci`
1. `npm run test-cloud`
1. Observe that tests pass
> Refactor match

- .eslintrc.yaml
- lib/array-types.js
- lib/deep-equal.test.js
- lib/is-array-type.js
- lib/is-array-type.test.js
- lib/match.js
- lib/match.test.js
This PR is a _Draft_ of improving `samsam` to detect more array types.
Support covers almost all Types of [typed arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays). Every Type is tested separatly (which increases the amount of tests alot, as seen for `match`).
While developing I was questioning if this really belongs into `samsam` or would make more sense in separat/dedicated package like `samsam-typed-arrays` or `samsam-extra-array`.
@mantoni @mroderick any thoughts?
> Add Support for TypedArrays

- lib/create-matcher.js
- lib/create-matcher/match-object.js
- lib/create-matcher/type-map.js
- lib/deep-equal.test.js
During fd5e59e8, we lost our bound deepEqual (`deepEqual.use(createMatcher)`) and ended up with a regular, unbound matcher-less one (`deepEqual`).
This means situations like the following have no matcher as they recur:
```
deepEqual(
{foo: [() => {}]},
match({foo: [match.func]})
)
```
Fixes sinonjs/sinon#2183 too
---
While this does in fact fix the issue, i'm not 100% happy with it.
Since these matchers were extracted, we're on the very edge of slipping into circular-dependency hell. In reality, those extracted matchers need their `deepEqual` bound to `createMatcher`, but `createMatcher` is what included them! So we can't (hence why i pass it through the type map factory in this PR).
What i suggest is you have a good think of why you have this `use(...)` function at all. Why would you …
> re-introduce bound deepEqual

- lib/create-matcher.test.js
- lib/create-matcher/match-object.js
The reintroduction of deepEqual in #160 missed a function argument when recursively calling matchObject so that any deepEquals were unable to evaluate custom matchers because matcher === undefined. 
This PR adds the missing function argument and a test to verify that it's working
2. `npm ci`
3. remove the fix and see that the new test fails to match properly
> Fix issue with nested array matching

- .circleci/config.yml
As can be seen at https://github.com/nodejs/Release, Node 8 reached
"end" of life on 2019-12-31, and is no longer actively supported.
We will stop testing in Node 8 and start testing in Node 13, which will
become the next LTS release from April 2020.
1. Observe that tests are no longer run in Node 8
1. Observe that tests are run in Node 13
> Drop support for Node 8

- package-lock.json
- package.json
While working with @hexeberlin, we observed that `@sinonjs/formatio` is not actually being used by `@sinonjs/samsam`.
As can be seen with searching the codebase, @sinonjs/formatio is never imported, and is thus not a direct dependency of @sinonjs/samsam.
```
┌────────────────────────┐                                                                                               
│    @sinonjs/commons    │◀──────────────────────────────────────────────────┐                                           
└────────────────────────┘                                                   │                                           
▲        ▲       ▲                                                       │                                           
│        │       │ …
```
> Remove unused @sinonjs/formatio

- docs/index.md
- lib/create-matcher.test.js
- lib/create-matcher/match-object.js
Updates the behavior of `match()` with objects so that it takes symbolic properties into account. Currently symbolic properties are ignored altogether for the purposes of matching.
This is a similar fix to #64, and extends that fix to the usage of `match()` with objects. It in fact borrows from that PR.
I ran into this when attempting to verify that my code was generating the correct queries with Sequelize after upgrading to the latest version, which uses Symbol keys extensively, using a set of symbols that are properties of the `Op` object for various query operations. My code was something like:
```
const findAllStub = Sinon.stub(User, "findAll")
User.findAll({
where: {
firstName: "John",
lastName: {
[Op.iLike]: "%son"
}
},
offset: 10,
limit: 20
}) …
```
> Evaluate symbol keys for object matchers

- lib/create-matcher.js
- lib/create-matcher.test.js
While we have `assert.json` in `referee`, I'd like to add `match.json` for use cases like these:
```js
// referee
assert.equals(request, {
header: {},
body: match.json({ some: 'value' })
});
// sinon
sinon.assert.calledOnceWith(callback, null, match.json({ some: 'value' }));
```
2. `npm ci`
3. `npm test`
> Add match.json

- .browserslistrc
- .eslintrc.yaml
- lib/create-matcher.js
- lib/create-matcher.test.js
- lib/create-matcher/assert-method-exists.js
- lib/create-matcher/assert-type.js
- lib/create-matcher/matcher-prototype.js
- lib/create-matcher/type-map.js
- lib/deep-equal-benchmark.js
- lib/deep-equal.js
- lib/deep-equal.test.js
- lib/is-array-type.test.js
- lib/iterable-to-string.js
- lib/match.test.js
- package-lock.json
- package.json
This PR upgrades ~`eslint-config-sinon`~ `@sinonjs/eslint-config` and fixes all uncovered lint violations.
Adopt the latest `@sinonjs/eslint-config` in order to allow modern JavaScript syntax and ease the maintenance burden of keeping all the development tools up to date.
https://hackmd.io/@mroderick/sinon-rfc-drop-legacy-browsers
* Add latest version of `@sinonjs/eslint-config` as `devDependency`
* Fix all lint violations
* Uninstall no longer needed linting dependencies
2. `npm ci`
3. `npm run lint`
4. Observe that there are no lint warnings or errors
> Use sinonjs eslint config

- .eslintrc.yaml
- lib/deep-equal.js
- lib/deep-equal.test.js
Fix issue #216 by explicitly checking Promise instances
I found that sinon spy `calledWith` does not properly check promises equality and always returns true.
Reported [here](https://github.com/sinonjs/sinon/issues/2345)
Simple fix, I've just added explicit Promise instance checking similar to how `Error` or `RegExp` are checked. I've also added a couple tests to verify it. I haven't added a test to check promises against other type of data as that was already working but I can add a explicit test for that case if you want.
1. `npm t` (or just check the ci)
> Fix deep equal comparison between promises

- lib/create-matcher.test.js
- lib/deep-equal.js
- lib/is-iterable.js
Fix issue https://github.com/sinonjs/sinon/issues/2400 by adding support for iterables.
The matchers currently don't account for Map and Set iterables. This was originally discovered in the issue linked above.
- I add a check for non-Array, non-Arguments iterables in the function. At this point primitive values are already handled.
- I transform both iterables to Arrays. I noticed that deep browser support is really important in this repo, so open to approaches on how folks want to do this. One idea I had was to polyfill `Array.from` using the recommendation from MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#polyfill
- This should also support deeply nested iterables
The tests describe a good process for trying to both reproduce the …
> Add support for iterables

- lib/deep-equal.js
- lib/deep-equal.test.js
Fix input's which add by PR #225 
Does not match when using [immutable.js](https://immutable-js.com/) such as the following
```js
assert.isTrue(samsam.deepEqual(
{ a: immutable.fromJS({ 'foo': 'bar', 'baz': [1] }) },
{ a: immutable.fromJS({ 'foo': 'bar', 'baz': [1] }) }
));
```
Before #225, it matches.
Fix to compare same nest.
1. `npm ci`
1. `npm test`
> Fix to compare input for iteratables.

- lib/deep-equal.js
- lib/issues.test.js
This PR contains a fix for #237 
1. `git checkout 57756a9efad21bedf07420efd1e3b3be0d7ae09a` (latest commit on `main`)
2. `npm ci`
3. `npm run test-headless`
4. Observe one test failing
5. `npm ci`
6. `npm run test-headless`
7. Observe all tests pass
> Fix #237: compare jQuery objects

- .github/workflows/main.yml
This PR drops support for Node 12 and adds support for 18 and 19.
See: https://github.com/nodejs/release#release-schedule
> Drop Node 12

- lib/create-matcher.test.js
- lib/create-matcher/match-object.js
Fix https://github.com/sinonjs/samsam/issues/233, adding a test case to verify
As the issue suggested, I've added an `identical()` check to exit the recursion if the expected and actual values of a key are identical objects (this catches circular objects and prevents calling back into `matchObject` infinitely).
TDD: new test causes a maximum call stack recursion error without the fix, passes with the fix. Rest of test suite passes.
> Fix matcher cyclic object infinite recursion issue

- lib/create-matcher.js
- package-lock.json
- package.json
lodash.get has been deprecated and consumers of samsam get the following deprecation warning during their npm install:
> npm warn deprecated lodash.get@4.4.2: This package is deprecated. Use the optional chaining (?.) operator instead.
Fixes issue: https://github.com/sinonjs/samsam/issues/253
2. `npm ci`
3. `npm run test`
> Remove dependency on the deprecated lodash.get

- .husky/pre-commit
- coverage.cjs
- docs/index.md
- lib/create-matcher.js
- lib/create-matcher.test.js
- lib/create-matcher/match-object.js
- lib/deep-equal.js
- lib/match.js
- package-lock.json
- package.json
- Upgrade mochify to @mochify/cli (esbuild-based)
- Replace nyc with c8 for test coverage
- ~~Migrate from lint-staged to husky pre-commit script~~
- ~~Commits now require successful runs of lint, prettier:check, build, test-check-coverage, and test-headless~~
- Fix formatting issue in index.md (prettier)
- nyc has not been actively maintained, c8 is a maintained alternative and is fairly compatible with nyc - Fixes: https://github.com/sinonjs/samsam/issues/250
- Similarly to other Sinon projects, need to upgrade Mochify to get security fixes - Fixes: https://github.com/sinonjs/samsam/issues/250
- ~~Current version of husky, has made the need for lint-staged redundant, and we can simplify the dependency tree by removing lint-staged.  The current lint-staged scripts also do not run tests, …
> Chore: toolchain upgrades

- package.json
mochify.webdriver.cjs is used to setup testing of samsam, and hence doesn't have unit tests.  The code coverage jobs/scripts fail currently.
We can exclude mochify.webdriver.cjs from code coverage
Github workflow check for this PR
> fix: ignore coverage for mochify.webdriver.cjs

- lib/deep-equal.js
- lib/deep-equal.test.js
Issue #251 was about samsam not being able to see that two Url objects were the same. This happened because it only compared keys on the object itself, not on the prototype. This meant fields that were synthetic/derived, but enumerable, would not be compared. URL objects, for instance would have 0 fields to compare. 
I do not think this made much sense, so I changed the comparison to include all enumerable props present on the entire prototype chain, as that is what one cares about: the intentionally exposed fields. This had basically no breaking effects I could see in the test suite, apart from a single case where we compared Arrays to the special Arguments object. This was negative for the same reason: the iterator symbol is only present on the Arguments object, not the array, but it is …
> Fix #251: compare props on the prototype chain

- .github/dependabot.yml
- .github/workflows/main.yml
- Removed version grouping to prevent major updates from blocking CI
- Reduced PR limit to 3 to match previous group count
- Fix permission issue for Dependabot auto merge
- Add support for CODECOV_TOKEN
- Remove code coverage report upload as a blocking workflow step
- The build is currently broken because of we recently set the main Branch as protected and CodeCov requires a token if the report is for a protected branch.
- The current Dependabot pull requests combine multiple packages if any based on their patch/minor/major version update.  That means a breaking change in a package in one of the groups can block all of the other packages from updating.
- There is misconfigure permission for Dependabot auto merge that will prevent the token for the github CLI to have insufficent …
> ci: adjust dependabot config and code coverage upload
