sinonjs/samsam

Readme.md

This PR changes the build badges to SVG for sharper readability ✨

Readme: use SVG build badge

---

.travis.yml

- Fix Travis node environments

Fix travis node env and add scripts

---

lib/samsam.test.js
package-lock.json
package.json

This PR replaces the `referee` dependency with `@sinonjs/referee`.
1. Observe that all tests pass on Travis
2. ?
3. Win!

Replace refree with @sinonjs/referee

---

.eslintignore
.eslintrc.yaml
.gitignore
.travis.yml
lib/samsam.js
package-lock.json
package.json
rollup.config.js

This PR prepares the repository for release.

Prepare repository for release

---

.travis.yml

Run tests in node 6, 8, 10

---

.min-wd
.travis.yml
package-lock.json
package.json

Adds cross-browser testing in the cloud and locally using Puppeteer
```
export SAUCE_USERNAME=sinonjs
export SAUCE_ACCESS_KEY=3a59ad42-cf59-foo-bar # credentials (available to all maintainers of Sinon)
npm run test-cloud
```

Add cross-browser testing

---

lib/deep-equal.js
lib/deep-equal.test.js
lib/get-class-name.js
lib/is-subset.js
package-lock.json
package.json

This PR fixes all the failing tests in IE11.
See #42 
You'll need to have Sauce Labs configured for `sinonjs` on your computer to be able to verify this PR.
3. `npm run test-cloud`

Fix all broken tests in IE11

---

package-lock.json
package.json

This allows use of hoisted functions, which unlocks an upcoming refactoring

Upgrade eslint-config-sinon

---

lib/engine-can-detect-arguments.js
lib/is-arguments.js
lib/is-arguments.test.js
package-lock.json
package.json

Increase coverage of is argument function

---

lib/match.js

Fixes #111 
1. coverage should now be 100%

Skip line from coverage as it should not be possible to reach it

---

lib/match.test.js

Match should returns false if subset array does not include a match

---

lib/deep-equal.test.js

Should be able to compare matchers

---

lib/create-matcher.js
lib/create-matcher.test.js
lib/deep-equal.test.js
lib/is-arguments.test.js
lib/match.test.js

Increase Coverage towards 💯 %
3. `npm run test-coverage`

increase coverage

---

package-lock.json
package.json
rollup.config.js

With 286d350 we bumped rollup to a new major version, which requires updates to the config.

Fix rollup config

---

.editorconfig
.eslintrc.yaml
jsdoc.conf.json

This PR just aligns the formatting of all `json` and `yaml` files

align json/yaml formatting

---

lib/deep-equal.js
lib/samsam.test.js

Instead of going back and forth in the comments in #124, I thought it would be easier for everyone if I just type up my suggested changes as a PR to a PR.
Prevent regressions in the public API by expressing expectations of it.
1. Observe that tests pass

Add tests for public API

---

lib/deep-equal.js
lib/samsam.js
lib/samsam.test.js

Export `isMap` to the public API
3. call `samsam.isMap(...)`

export is-map function

---

lib/match.js
lib/match.test.js

Add support fo Map in match function

---

README.md

Use CircleCI build badge in README.md

---

package-lock.json

Upgrade insecure devDependencies

---

package-lock.json
package.json

Help write a changelog and avoid missing tags in shared repository

Use @studio/changes

---

package-lock.json
package.json

This will remove some duplication in Sinon, see https://github.com/sinonjs/sinon/issues/2224

Bump formatio to latest major

---

package.json

1. `npm ci`
1. <your-steps-here>

Add configuration for commit hook

---

lib/deep-equal.js
lib/is-iterable.test.js

Follow up to https://github.com/sinonjs/samsam/pull/225 to bring code coverage back up so we can release.

Follow up for "Support for Iterables" to increase code coverage

---

package-lock.json
package.json

1. `npm ci`
1. <your-steps-here>

Upgrade mocha to latest

---

.github/workflows/main.yml

1. `npm ci`
1. <your-steps-here>

Workflow improvements

---

AUTHORS

docs: Update AUTHORS wrong email

---

.github/workflows/main.yml
mochify.webdriver.cjs
package-lock.json
package.json
test-cloud.sh

The last PR [broke the build](https://github.com/sinonjs/samsam/actions/runs/16824766118/job/47658580692), as the lock file changed from version 2 to 3. 
This made me realise that the PR did not trigger the workflow. It turns out it only triggers on pushes to this repository (of course), which will only affect the _main_ branch. I fixed this here.

Upgrade package-lock.json version and add workflow runs on PRs
